---
- name: My fedora44 configuration
  hosts: localhost
  connection: local

  roles:
    - vscode
    - flatpak
    - gnome
    - dnf
    - syncthing
    - ssh-client
    - git

  tasks:
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "mishaid-{{ ansible_facts['board_name'] }}"
        use: systemd

    - name: Set global umask
      ansible.builtin.blockinfile:
        path: /etc/bashrc
        append_newline: true
        prepend_newline: true
        block: "umask 077"
      become: true

    - name: Update whole system
      ansible.builtin.dnf:
        name: '*'
        state: latest
      become: true

# TODO: VSCode module installation?
