# dconf settings
- name: Set dark theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"
    state: present

- name: Set accent color
  community.general.dconf:
    key: "/org/gnome/desktop/interface/accent-color"
    value: "'blue'"
    state: present

- name: Set window buttons layout
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "'appmenu:minimize,maximize,close'"
    state: present

- name: Set input source
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'us'), ('xkb', 'ru')]"
    state: present

- name: Set time format
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'24h'"
    state: present

- name: Set first day of the week
  community.general.dconf:
    key: "/org/gnome/desktop/calendar/week-start-day"
    value: "'monday'"
    state: present

- name: Set home folder shortcut
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/home"
    value: "['<Super>e']"
    state: present

- name: Set hide all windows shortcut
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/show-desktop"
    value: "['<Super>d']"
    state: present

- name: Set power-off shortcut
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/shutdown"
    value: "['<Control><Alt>Delete']"
    state: present

- name: Disable log out shortcut
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/logout"
    value: "@as []"
    state: present

# Gnome extensions
- name: Install Gnome extension manager
  community.general.flatpak:
    name: com.mattjakeman.ExtensionManager
    state: present

- name: Download Gnome Dash To Dock
  ansible.builtin.get_url:
    url: https://github.com/micheleg/dash-to-dock/releases/download/extensions.gnome.org-v105/dash-to-dock@micxgx.gmail.com.zip
    dest: /tmp/dash-to-dock@micxgx.gmail.com.zip
    owner: mishaid
    mode: '0644'

- name: Install Gnome Dash To Dock
  ansible.builtin.command:
    cmd: gnome-extensions install /tmp/dash-to-dock@micxgx.gmail.com.zip --force
    creates: /home/mishaid/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/metadata.json

- name: Download Gnome Blur My Shell
  ansible.builtin.get_url:
    url: https://github.com/aunetx/blur-my-shell/releases/download/v72/blur-my-shell@aunetx.shell-extension.zip
    dest: /tmp/blur-my-shell@aunetx.shell-extension.zip
    owner: mishaid
    mode: '0644'

- name: Install Gnome Blur My Shell
  ansible.builtin.command:
    cmd: gnome-extensions install /tmp/blur-my-shell@aunetx.shell-extension.zip --force
    creates: /home/mishaid/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/metadata.json

- name: Download Gnome AppIndicator
  ansible.builtin.get_url:
    url: https://github.com/ubuntu/gnome-shell-extension-appindicator/releases/download/v64/appindicatorsupport@rgcjonas.gmail.com.zip
    dest: /tmp/appindicatorsupport@rgcjonas.gmail.com.zip
    owner: mishaid
    mode: '0644'

- name: Install Gnome AppIndicator
  ansible.builtin.command:
    cmd: gnome-extensions install /tmp/appindicatorsupport@rgcjonas.gmail.com.zip
    creates: /home/mishaid/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/metadata.json

- name: Download Gnome Gtk4 Desktop Icons NG
  ansible.builtin.get_url:
    url: https://gitlab.com/smedius/desktop-icons-ng/-/jobs/14292421007/artifacts/raw/dist/gtk4-ding@smedius.gitlab.com.zip
    dest: /tmp/gtk4-ding@smedius.gitlab.com.zip
    owner: mishaid
    mode: '0644'

- name: Install Gnome Gtk4 Desktop Icons NG
  ansible.builtin.command:
    cmd: gnome-extensions install /tmp/gtk4-ding@smedius.gitlab.com.zip
    creates: /home/mishaid/.local/share/gnome-shell/extensions/gtk4-ding@smedius.gitlab.com/metadata.json

- name: Copy Gnome extension config file
  ansible.builtin.copy:
    src: my_ext_bak.txt
    dest: /tmp/my_ext_bak.txt
    owner: mishaid
    group: mishaid
    mode: '0644'

- name: Restore Gnome extension settings from file
  ansible.builtin.shell:
    cmd: dconf load /org/gnome/shell/extensions/ < /tmp/my_ext_bak.txt
  changed_when: false

# Gnome icons and cursor

- name: Creat ~/.icon
  ansible.builtin.file:
    path: /home/mishaid/.icons
    state: directory
    owner: mishaid
    group: mishaid
    mode: '770'

- name: Exteract icons theme
  ansible.builtin.unarchive:
    src: Fluent.tar.xz
    dest: /home/mishaid/.icons/
    owner: mishaid
    group: mishaid
    mode: '770'

- name: Exteract cursor theme
  ansible.builtin.unarchive:
    src: volantes_cursors.tar.xz
    dest: /home/mishaid/.icons/
    owner: mishaid
    group: mishaid
    mode: '770'

- name: Set cursor theme
  ansible.builtin.command:
    cmd: gsettings set org.gnome.desktop.interface cursor-theme 'volantes_cursors'
  changed_when: false

- name: Set icon theme
  ansible.builtin.command:
    cmd: gsettings set org.gnome.desktop.interface icon-theme 'Fluent'
  changed_when: false
